//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlcoBear.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlcoBear.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imgAdd {
            get {
                object obj = ResourceManager.GetObject("imgAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imgCancel {
            get {
                object obj = ResourceManager.GetObject("imgCancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imgContragents {
            get {
                object obj = ResourceManager.GetObject("imgContragents", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imgDownload {
            get {
                object obj = ResourceManager.GetObject("imgDownload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imgOk {
            get {
                object obj = ResourceManager.GetObject("imgOk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imgRefresh {
            get {
                object obj = ResourceManager.GetObject("imgRefresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imgRequest {
            get {
                object obj = ResourceManager.GetObject("imgRequest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imgReturns {
            get {
                object obj = ResourceManager.GetObject("imgReturns", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imgSend {
            get {
                object obj = ResourceManager.GetObject("imgSend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imgSettings {
            get {
                object obj = ResourceManager.GetObject("imgSettings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;ns:Documents Version=&quot;1.0&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:ns=&quot;http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01&quot; xmlns:pref=&quot;http://fsrar.ru/WEGAIS/ProductRef_v2&quot; xmlns:awr=&quot;http://fsrar.ru/WEGAIS/ActWriteOff_v2&quot; xmlns:ce=&quot;http://fsrar.ru/WEGAIS/CommonEnum&quot;&gt;
        ///	&lt;ns:Owner&gt;
        ///		&lt;ns:FSRAR_ID&gt;{0}&lt;/ns:FSRAR_ID&gt;
        ///	&lt;/ns:Owner&gt;
        ///	&lt;ns:Document&gt;
        ///		&lt;ns:ActWriteOff_v2&gt;
        ///			&lt;awr:Header&gt;
        ///				&lt;awr:ActNumber&gt;{1}&lt;/awr:ActNumber&gt;
        ///				&lt;awr:ActDate&gt;{2}&lt;/awr:ActDate&gt;
        ///				&lt;awr [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string XMLPattern_ActWriteOff {
            get {
                return ResourceManager.GetString("XMLPattern_ActWriteOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ns:Documents Version=&quot;1.0&quot;	xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:ns=&quot;http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01&quot; xmlns:qp=&quot;http://fsrar.ru/WEGAIS/QueryParameters&quot;&gt;
        ///	&lt;ns:Owner&gt;
        ///		&lt;ns:FSRAR_ID&gt;{0}&lt;/ns:FSRAR_ID&gt;
        ///	&lt;/ns:Owner&gt;
        ///	&lt;ns:Document&gt;
        ///		&lt;ns:QueryNATTN&gt;
        ///			&lt;qp:Parameters&gt;
        ///				&lt;qp:Parameter&gt;
        ///					&lt;qp:Name&gt;КОД&lt;/qp:Name&gt;
        ///					&lt;qp:Value&gt;{0}&lt;/qp:Value&gt;
        ///				&lt;/qp:Parameter&gt;
        ///			&lt;/qp:Parameters&gt;
        ///		&lt;/ns:QueryNATTN&gt;
        ///	&lt;/ns:Document&gt;
        ///&lt;/ns:Documents&gt;.
        /// </summary>
        public static string XmlPattern_QueryNATTN {
            get {
                return ResourceManager.GetString("XmlPattern_QueryNATTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;ns:Documents Version=&quot;1.0&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:ns=&quot;http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01&quot; xmlns:oref=&quot;http://fsrar.ru/WEGAIS/ClientRef&quot; xmlns:qp=&quot;http://fsrar.ru/WEGAIS/QueryParameters&quot;&gt;
        ///	&lt;ns:Owner&gt;
        ///		&lt;ns:FSRAR_ID&gt;{0}&lt;/ns:FSRAR_ID&gt;
        ///	&lt;/ns:Owner&gt;
        ///	&lt;ns:Document&gt;
        ///		&lt;ns:QueryClients&gt;
        ///			&lt;qp:Parameters&gt;
        ///				&lt;qp:Parameter&gt;
        ///					&lt;qp:Name&gt;{1}&lt;/qp:Name&gt;
        ///					&lt;qp:Value&gt;{2}&lt;/qp:Value&gt;
        ///				&lt;/qp:Parameter&gt;
        ///			&lt;/qp:Parameters&gt;
        ///		&lt;/ns:QueryCl [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string XMLPattern_QueryPartner {
            get {
                return ResourceManager.GetString("XMLPattern_QueryPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;ns:Documents Version=&quot;1.0&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:ns=&quot;http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01&quot; xmlns:qp=&quot;http://fsrar.ru/WEGAIS/QueryParameters&quot;&gt;
        ///	&lt;ns:Owner&gt;
        ///		&lt;ns:FSRAR_ID&gt;{0}&lt;/ns:FSRAR_ID&gt;
        ///	&lt;/ns:Owner&gt;
        ///	&lt;ns:Document&gt;
        ///		&lt;ns:QueryRests /&gt;
        ///	&lt;/ns:Document&gt;
        ///&lt;/ns:Documents&gt;.
        /// </summary>
        public static string XMLPattern_QueryRests {
            get {
                return ResourceManager.GetString("XMLPattern_QueryRests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ns:Documents Version=&quot;1.0&quot;	xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:ns=&quot;http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01&quot; xmlns:c=&quot;http://fsrar.ru/WEGAIS/Common&quot; xmlns:oref=&quot;http://fsrar.ru/WEGAIS/ClientRef&quot; xmlns:pref=&quot;http://fsrar.ru/WEGAIS/ProductRef&quot; xmlns:wb= &quot;http://fsrar.ru/WEGAIS/TTNSingle&quot;&gt;
        ///	&lt;ns:Owner&gt;
        ///		&lt;ns:FSRAR_ID&gt;{0}&lt;/ns:FSRAR_ID&gt;
        ///	&lt;/ns:Owner&gt;
        ///	&lt;ns:Document&gt;
        ///		&lt;ns:WayBill&gt;
        ///			&lt;wb:Header&gt;
        ///				&lt;wb:NUMBER&gt;{1}&lt;/wb:NUMBER&gt;
        ///				&lt;wb:Date&gt;{2}&lt;/wb:Date&gt;
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string XMLPattern_WayBill {
            get {
                return ResourceManager.GetString("XMLPattern_WayBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;ns:Documents Version=&quot;1.0&quot; 
        ///		xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///		xmlns:ns=  &quot;http://fsrar.ru/WEGAIS/WB_DOC_SINGLE_01&quot;
        ///		xmlns:oref=&quot;http://fsrar.ru/WEGAIS/ClientRef&quot;
        ///		xmlns:pref=&quot;http://fsrar.ru/WEGAIS/ProductRef&quot;
        ///		xmlns:wa=  &quot;http://fsrar.ru/WEGAIS/ActTTNSingle&quot;&gt;
        ///	&lt;ns:Owner&gt;
        ///		&lt;ns:FSRAR_ID&gt;{0}&lt;/ns:FSRAR_ID&gt;
        ///	&lt;/ns:Owner&gt;
        ///	&lt;ns:Document&gt;
        ///		&lt;ns:WayBillAct&gt;
        ///			&lt;wa:Header&gt;
        ///				&lt;wa:IsAccept&gt;{1}&lt;/wa:IsAccept&gt;
        ///				&lt;wa:ACTNUMBER&gt;{2}&lt;/wa:ACTNUMBER&gt;
        ///				&lt;w [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string XMLPattern_WayBillAct {
            get {
                return ResourceManager.GetString("XMLPattern_WayBillAct", resourceCulture);
            }
        }
    }
}
